services:
  web: 
    build:
      context: app
      target: builder
    environment:
      - PYTHONUNBUFFERED=1
    stop_signal: SIGINT
    volumes:
      - './app:/app'
    ports:
      - '8000:8000'
    restart: always
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:10-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=weatherscraper
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on: 
      - web
    networks:
      - frontnet
volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet: